import Headercomponent from "@/components/home/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen w-full`}
      >
        <Headercomponent />
        <main className="flex-1 flex">
          {children}
        </main>
        <footer className="text-center bg-gray-200 py-2">Footer</footer>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
